name: Commit

on:
  push:
    branches:
      - 'master'

env:
  COMMIT_OWNER: ${{ github.event.pusher.name }}
  COMMIT_SHA: ${{ github.sha }}
  PIPELINE_ID: ${{ github.run_number }}

jobs:
  snapshot_tests:
    name: Test against snapshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Snapshot Tests
        run: |
          ./gradlew clean prepush --stacktrace
      - name: Track error step
        uses: spring-projects/track-build-errors-action@v1
        if: ${{ failure() }}
        with:
          job-name: ${{ github.job }}
      - name: Export errors file
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: errors
          path: job-${{ github.job }}.txt
